workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 18
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web assets
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-build:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 18
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web assets
        script: npx cap sync ios
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination 'generic/platform=iOS Simulator' -configuration Debug
    artifacts:
      - ios/App/build/**/*.app
