workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 21
      node: 20
      groups:
        - android_signing
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web assets
        script: npx cap sync android
      - name: Setup keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/aspekt5-release-key.jks
          echo "storeFile=aspekt5-release-key.jks" > android/app/signing.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android/app/signing.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/app/signing.properties
          echo "keyPassword=$CM_KEYSTORE_PASSWORD" >> android/app/signing.properties
      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
